### ISSUE TITLE
Procedure documentation error in Operations Manual

### ISSUE THREAD

**Issue by studentlaw** [neo4j/neo4j-documentation#102]
In the Operations Manual, in appendix A.2. Built-in procedures, the signature of the `AwaitIndex()` procedure is incorrectly documented.

It currently reads:

`CALL db.awaitIndex(label, property, timeout)`

but that should be:

`CALL db.awaitIndex(":Label(property)", timeoutSeconds)`

**Comment by jjaderberg** [comment]
Done (forgot to close)
