### ISSUE TITLE
CSV import tool: file groups are not required to be enclosed in quotation marks

### ISSUE THREAD

**Issue by szarnyasg** [neo4j/neo4j-documentation#1121]
The documentation states "note how the file groups are enclosed in quotation marks in the command" but the command does not use quotation marks. In fact, quotation marks are not required for the loader to work correctly.

A potential fix would be adding quotation marks in the code or removing the note from the documentation.

![image](https://user-images.githubusercontent.com/1402801/120002844-7c57cc00-bfd5-11eb-8825-39b61b327317.png)

Location in the source code:
* https://github.com/neo4j/neo4j-documentation/blob/30ee91dc240681f1c8dcf8b80643a2e7fa3c934d/import-tool/src/docs/ops/import-tool.asciidoc#using-separate-header-files
* https://github.com/neo4j/neo4j-documentation/blob/30ee91dc240681f1c8dcf8b80643a2e7fa3c934d/import-tool/src/test/java/org/neo4j/tooling/ImportToolDocIT.java#L178-L180

**Comment by renetapopova** [comment]
Thank you so much for reporting this @szarnyasg, sounds like a bug in the documentation.

**Comment by martin-neotech** [comment]
https://github.com/neo-technology/neo4j-manual-modeling/pull/2103
