### ISSUE TITLE
Value of the list type cannot be stored as properties

### ISSUE THREAD

**Issue by czpmango** [neo4j/neo4j-documentation#1286]
The documentation([values and types](https://github.com/neo4j/neo4j-documentation/blob/dev/cypher/cypher-docs/src/docs/dev/syntax/values.asciidoc#cypher-expressions)) says that `value of the list type` cannot be stored as properties, but this is inconsistent with my tests.

![image](https://user-images.githubusercontent.com/26356194/138658754-7d6a7674-b213-45d2-a730-5c537a5c4c3f.png)

my test:
```
neo4j@neo4j> create (:lable{prop:[2,3,4]});
0 rows available after 39 ms, consumed after another 0 ms
Added 1 nodes, Set 1 properties, Added 1 labels
```

**Comment by mnd999** [comment]
Homogeneous lists of simple types can also be stored as properties, but heterogeneous lists may not.

**Comment by czpmango** [comment]
ACK.
