### ISSUE TITLE
Issue while connecting NEO4J to JASPERSOFT

### ISSUE THREAD

**Issue by jyothi1121** [neo4j/neo4j-documentation#140]
I am trying to connect NEO4J to JASPER SOFT. I referred below link for connection process.
http://neo4j-contrib.github.io/neo4j-jdbc/#_jdbc_compatibility
STEP 1 "Creating new Data Adapters" is successful and Database is successfully connected to JDBC.

But in STEP 2 "Retrieve Columns from Database" , i am facing an issue while fetching data from NEO4J database which is a part of creating JASPER report.
I am getting an error like  "GETTING METADATA FOR NEO4J.....PLEASE WAIT...".
I am not sure whether this issue is regarding driver problem or URL problem.
Please provide me a solution for this.

**Comment by jjaderberg** [comment]
@jyothi1121 This repository contains tools and tests for the Neo4j documentation (https://neo4j.com/docs/).
For problems with the Neo4j JDBC driver you should open an issue with that project's issue tracker at https://github.com/neo4j-contrib/neo4j-jdbc/issues. If you have questions on how to use drivers and other products in the Neo4j ecosystem (or Neo4j itself) you could also join the Neo4j Users Slack and ask your questions there.
