### ISSUE TITLE
suggestion, add list of known Cypher parsers at https://neo4j.com/docs/cypher-manual/current/ and merge documentation

### ISSUE THREAD

**Issue by masta99wrfvsHsa** [neo4j/neo4j-documentation#1493]
showing a brief list of known parser is very useful for user to test.
be it a web service by neo4j or third party or neo4j official cli parser.Its will help newbie to try out.

merging.
https://neo4j.com/docs/cypher-manual/current/syntax/

https://neo4j.com/docs/cypher-refcard/current/

or maybe change>
Cypher syntax basics

to 
Cypher Quick Cheat sheet

**Comment by martin-neotech** [comment]
Thanks for the suggestion @masta99wrfvsHsa, there is a WIP that will soon be released, with a new style for the Cypher Refcard (Cypher Cheat Sheet). This will give a better overview and more complete examples of the Cypher Query Language.
