### ISSUE TITLE
Broken link in 3.3.13. CREATE UNIQUE

### ISSUE THREAD

**Issue by codebling** [neo4j/neo4j-documentation#2]
The link to MERGE seems to be broken in [3.3.13. CREATE UNIQUE](http://neo4j.com/docs/developer-manual/current/cypher/#query-create-unique) 
![screenshot](https://cloud.githubusercontent.com/assets/1073841/19709132/276a9f2c-9af2-11e6-8d67-d679243ffff8.png)

I'm not familiar enough with Asciidoc to figure out why it's not working, but the problem appears to lie [in this file](https://github.com/neo4j/neo4j-documentation/blob/242bab483816397fedb71fb0a6ba186451fe2c07/manual/cypher/cypher-docs/src/docs/dev/ql/create-unique/index.asciidoc).

**Comment by jjaderberg** [comment]
@codebling We just published updates to the documentation which include a fix for the broken link. Thanks for reporting!
