### ISSUE TITLE
Docker documentation listing non-existing environment variables

### ISSUE THREAD

**Issue by oschlueter** [neo4j/neo4j-documentation#234]
Hey,

the [operations manual for Docker installation section 2.5.3](https://neo4j.com/docs/operations-manual/current/installation/docker/) mentions the environment variables `NEO4J_CACHE_MEMORY` and `NEO4J_HEAP_MEMORY` (as used in [Neo4j 2.3](https://github.com/neo4j/docker-neo4j/blob/master/src/2.3/docker-entrypoint.sh))  which have since [been replaced](https://github.com/neo4j/docker-neo4j/blob/master/src/3.4/docker-entrypoint.sh). 

Could you update that part of the operations manual please?

**Comment by davidoliverSP2** [comment]
fixed in https://github.com/neo-technology/neo4j-manual-modeling/pull/616 for 3.3 onwards
