### ISSUE TITLE
3.5.2. Constraints - Unable to ASSERT exists(book.isbn)

### ISSUE THREAD

**Issue by naisanza** [neo4j/neo4j-documentation#27]
I'm unable to successfully run the `ASSERT exists(book.isbn)` command listed in http://neo4j.com/docs/developer-manual/current/cypher/schema/constraints/

**Neo4j version:** [3.1.0 community Dockerfile](https://github.com/neo4j/docker-neo4j-publish/blob/36ac547bcffcce2c7c0f249b340d062ba08e2598/3.1.0/community/Dockerfile)
**Operating system:** Ubuntu 16.10 
**API/Driver:** Kubernetes/Cypher

```
CREATE CONSTRAINT ON (book:Book) ASSERT book.isbn IS UNIQUE
Added 1 constraint, statement completed in 111 ms.
```

```
CREATE (book:Book { isbn: '1449356265', title: 'Graph Databases' })
Added 1 label, created 1 node, set 2 properties, statement completed in 16 ms.
```

```
CREATE CONSTRAINT ON (book:Book) ASSERT exists(book.isbn)
Unable to create CONSTRAINT ON ( book:Book ) ASSERT exists(book.isbn)
```

Error Response Data:
```
{
  "signature": 127,
  "fields": [
    {
      "code": "Neo.DatabaseError.Schema.ConstraintCreationFailed",
      "message": "Unable to create CONSTRAINT ON ( book:Book ) ASSERT exists(book.isbn)"
    }
  ],
  "timings": {
    "type": "client"
  }
}
```

**Comment by jjaderberg** [comment]
Hi @naisanza, property existence constraints are only avilable in Neo4j Enterprise Edition. Node uniqueness constraints, however, are avialable in both Community and Enterprise editions.

**Comment by jfbso** [comment]
LOL so you give a tutorial that bugs with the commands you give within? now that's open source!

:play https://guides.neo4j.com/reco-oscon/01_similar_groups_by_topic.html
