### ISSUE TITLE
property-container input is deprecated

### ISSUE THREAD

**Issue by szarnyasg** [neo4j/neo4j-documentation#36]
According to the documentation, the [`keys()`](https://neo4j.com/docs/developer-manual/current/cypher/functions/list/#functions-keys) and the [`id()`](https://neo4j.com/docs/developer-manual/current/cypher/functions/scalar/#functions-id) functions expect a `property-container` as their inputs, while the [`properties()`](https://neo4j.com/docs/developer-manual/current/cypher/functions/scalar/#functions-properties) function expects an `expression`, which is _"an expression that returns a node, a relationship, or a map"_.

Of these, only the latter is precise - both `keys()` and `properties()` accept expressions as their inputs (tested with 3.0.7 and 3.1.1).

Using this dataset,
```
CREATE ()-[r:REL {name: "x", value: 1}]->()
```
running this query,
```
MATCH ()-[r*]->()
RETURN properties(r[0]), keys(r[0]), id(r[0])
```
results in:
```
╒════════════════════════╤════════════════╤══════════╕
│"properties(r[0])"      │"keys(r[0])"    │"id(r[0])"│
╞════════════════════════╪════════════════╪══════════╡
│{"name":"x","value":"1"}│["name","value"]│"85"      │
└────────────────────────┴────────────────┴──────────┘
```

I think the `property-container` input (used in the documentation) is no longer valid - all of these functions allow the user to specify an expression returning the appropriate elements (nodes/relationships and for the `property()` function, maps).

**Comment by petraselmer** [comment]
Thanks very much @szarnyasg - it's now been merged
