### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by LarsKumbier** [neo4j/neo4j-documentation#364]
In the [documentation](https://neo4j.com/developer/guide-create-neo4j-browser-guide/#browser-guides) is a small mistake:

```
add play command as setting in neo4j.conf

browser.post_connect_cmd=play <guide url or name>

browser.post_connect_cmd=play http://guides.neo4j.com/apoc
# or
browser.post_connect_cmd=play intro
```

result in a "command not found" due to a missing colon (`:`). Instead it should say:

```
add play command as setting in neo4j.conf

browser.post_connect_cmd=:play <guide url or name>

browser.post_connect_cmd=:play http://guides.neo4j.com/apoc
# or
browser.post_connect_cmd=:play intro
```

Funny enough, the method via the url parameter works fine:

```
http://localhost:7474/browser?cmd=play&arg=northwind%20graph
```

Visiting this url will properly start the northwind-guide after pressing enter.

**Comment by davidoliverSP2** [comment]
Thanks @LarsKumbier 

Unfortunately I can't action this from this repository, so I've raised a new issue on our community site, where one of my colleagues can pick this up and make the amendment: 
https://community.neo4j.com/t/mistake-in-the-create-a-custom-neo4j-browser-guide/8446
