### ISSUE TITLE
Heavy CPU usage of Documentation Website

### ISSUE THREAD

**Issue by Phylodome** [neo4j/neo4j-documentation#405]
I'm not exactly sure where to report this, so I apologize if this is the wrong place to do so.

When working w/ Neo4j, I usually keep a Neo4j documentation tab open in my (Chrome) browser. Quite frequently I will notice my laptop's fans going crazy, and check Chrome's Task Manager.

9 times out of 10 it's the the Neo4j documentation page, consuming 100% CPU. It doesn't appear to matter which doc page I'm on, or how much I've interacted w/ the page. Over time it's pretty much guaranteed to eventually consume the entirety of CPU resources available.

In general I love working w/ Neo4j, but this isn't the most pleasant part.

**Comment by davidoliverSP2** [comment]
Many thanks for reporting this unusual behavior.

Unfortunately, we've tested this and not been able to recreate this using Chrome, or any other browser. If you continue to observe this spike in CPU when accessing the Neo4j website & docs, please could you reopen this issue (or open a new one), with as much information as possible about what else you are running on your machine.

**Comment by Phylodome** [comment]
Hey @davidoliverSP2,

Definitely still happening for me. Appears to be something related to your use of Service Workers:

<img width="634" alt="Screen Shot 2019-11-28 at 1 26 34 PM" src="https://user-images.githubusercontent.com/241837/69832414-fd68b400-11e2-11ea-937b-a1cb2e798e4f.png">

CPU usage was fluctuating b/w the levels depicted in this screencap at the lower bound, and >90%. Doesn't seem correlated with anything else I'm running on my machine. If I open a fresh Chrome tab as the only running executable, this still occurs eventually.

**Comment by davidoliverSP2** [comment]
Ok - thanks for the further info. I'll reopen this and do some more investigations!

**Comment by Phylodome** [comment]
No problem. The odd aspect is that I see this appear across multiple different Neo4j pages, with presumably separate codebases. 

The above, for example, was on the community page, while the two below were on documentation pages. Perhaps it's an embed used for user tracking, or something of the kind, given that Chrome uses said "subframes" to isolate embedded iframes within their own process?

<img width="634" alt="Screen Shot 2019-11-29 at 1 18 17 PM" src="https://user-images.githubusercontent.com/241837/69906198-95e26e00-1374-11ea-93cd-f8c1c9dc51a0.png">
<img width="634" alt="Screen Shot 2019-11-29 at 2 38 00 PM" src="https://user-images.githubusercontent.com/241837/69906199-95e26e00-1374-11ea-9439-442aa23d318d.png">

**Comment by MarkWoulfeNeo4j** [comment]
Hi @Phylodome, looking at the chrome task manager now, and given the age of this issue, it does not appear to still be an issue. Feel free to respond if you are still running into this.
