### ISSUE TITLE
Minor auto-correct issues and typos

### ISSUE THREAD

**Issue by KDean-Dolphin** [neo4j/neo4j-documentation#97]
I have come across a few minor typos in the documentation.

- In "3.2.2.1. Expressions in general", "myFancyVariable, A name with weird stuff in it[]!" should have a box around the two together, not a box around each.
- In "3.2.2.1. Expressions in general", the path pattern "(a)-→()←-(b)" has what looks like auto-corrected arrows rather than "-->" and "<--".
- In "3.2.5.1. Operators at a glance", the "<=" operator has been auto-corrected to "⇐".

**Comment by jjaderberg** [comment]
fixed by bf5429966cc9b0c1ecd3e166f099c7beb31ac00e and aad5f1cacda7deb09ed1c1390026e7ab5933542f

Thanks @KDean-Dolphin!
